# Generated by Django 4.2.16 on 2024-11-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_post_found"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/"),
        ),
    ]
