# Generated by Django 4.2.16 on 2024-11-19 01:48

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_message_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=forum.models.post_picture_path
            ),
        ),
    ]
