# Generated by Django 4.2.16 on 2024-11-03 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_post_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="likes",),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
