# Generated by Django 4.2.16 on 2024-11-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="latitude",
            field=models.FloatField(default=43.4722893),
        ),
        migrations.AddField(
            model_name="post",
            name="longitude",
            field=models.FloatField(default=-80.5474325),
        ),
    ]
