# Generated by Django 4.2.16 on 2024-11-16 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
